force-app/main/default/objects/bedRocks_location__mdt/bedRocks_location__mdt.object-meta.xml
<CustomObject>
    <label>BedRock Location</label>
    <pluralLabel>BedRock Locations</pluralLabel>
</CustomObject>

force-app/main/default/objects/bedRocks_location__mdt/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/bedRocks_location__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/bedRocks_location__mdt/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/bedRocks_location__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/bedRocks_location__mdt/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BedRockLocationMetadataController.cls
public with sharing class BedRockLocationMetadataController {


    /**
     * Get the head quarter location from the custom metadata
     * @return List<bedRocks_location__mdt>
     */
    @AuraEnabled(cacheable=true)
    public static List<bedRocks_location__mdt> getHeadQuarterLocation() {
        List<bedRocks_location__mdt> locationMetadataList = [SELECT Id, City__c, Country__c, PostalCode__c, State__c, Street__c, value__c FROM bedRocks_location__mdt];
        if (locationMetadataList.isEmpty()) {
            throw new AuraHandledException(
                'Custom metadata record BedRock_HeadQuarter was not found for bedRocks_location__mdt.'
            );
        }

        return locationMetadataList;
    }
}